on:
  push:
    branches:
      - master

permissions:
  contents: read
  id-token: write
  pages: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
      pages: write
      actions: read

    steps:
      # downloads the repo onto the vm
      - uses: actions/checkout@v4

      - uses: actions/configure-pages@v4

      - uses: actions/upload-pages-artifact@v4
        with:
          path: ./
      #changed
      - uses: actions/deploy-pages@v4
      - run: echo "working"
