on:
  push:
    branches:
      - master
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # downloads the repo onto the vm
      - uses: actions/checkout@v4

      - uses: actions/configure-pages@v2

      - uses: actions/upload-pages-artifact@v1
        with:
          path: ./

      - uses: actions/deploy-pages@v1
      - run: echo "working"
