on:
  push:
    branches:
      - master

permissions:
  contents: read
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # downloads the repo onto the vm
      - uses: actions/checkout@v4

      - uses: actions/configure-pages@v4

      - uses: actions/upload-pages-artifact@v4
        with:
          path: ./

      - uses: actions/deploy-pages@v4
      - run: echo "working"
